//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.HealthAndSafetyIncidents
        {
            get
            {
                return this.HealthAndSafetyIncidents;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> __HealthAndSafetyIncidents
        {
            get
            {
                if (this.___HealthAndSafetyIncidents == null)
                {
                    this.___HealthAndSafetyIncidents = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident>(
                        this,
                        "HealthAndSafetyIncidents",
                        () => this._HealthAndSafetyIncidents,
                        e => global::System.Object.Equals(e.HealthAndSafetyIncident_Employee, this.Id));
                }
                return this.___HealthAndSafetyIncidents;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> ___HealthAndSafetyIncidents;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ReportedByHealthAndSafetyIncidents
        {
            get
            {
                return this.ReportedByHealthAndSafetyIncidents;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> __ReportedByHealthAndSafetyIncidents
        {
            get
            {
                if (this.___ReportedByHealthAndSafetyIncidents == null)
                {
                    this.___ReportedByHealthAndSafetyIncidents = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident>(
                        this,
                        "ReportedByHealthAndSafetyIncidents",
                        () => this._ReportedByHealthAndSafetyIncidents,
                        e => global::System.Object.Equals(e.HealthAndSafetyIncident_Employee1, this.Id));
                }
                return this.___ReportedByHealthAndSafetyIncidents;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> ___ReportedByHealthAndSafetyIncidents;
        
    }
    #endregion
    
    #region HealthAndSafetyIncident
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class HealthAndSafetyIncident :
        global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass.IImplementation
    {
        partial void OnHealthAndSafetyIncident_Employee1Changed()
        {
            this.___OnPropertyChanged("HealthAndSafetyIncident_Employee1");
            this.___OnPropertyChanged("ReportedBy");
        }
        
        partial void OnIncidentStatus_HealthAndSafetyIncidentChanged()
        {
            this.___OnPropertyChanged("IncidentStatus_HealthAndSafetyIncident");
            this.___OnPropertyChanged("IncidentStatus");
        }
        
        partial void OnHealthAndSafetyIncident_EmployeeChanged()
        {
            this.___OnPropertyChanged("HealthAndSafetyIncident_Employee");
            this.___OnPropertyChanged("ReportedTo");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnReferenceChanged()
        {
            this.___OnPropertyChanged("Reference");
        }
        
        partial void OnIncidentDateChanged()
        {
            this.___OnPropertyChanged("IncidentDate");
        }
        
        partial void OnIncidentDescriptionChanged()
        {
            this.___OnPropertyChanged("IncidentDescription");
        }
        
        partial void OnHappenedAtWorkChanged()
        {
            this.___OnPropertyChanged("HappenedAtWork");
        }
        
        partial void OnPersonsInjuredChanged()
        {
            this.___OnPropertyChanged("PersonsInjured");
        }
        
        partial void OnTargetInvestigationDateChanged()
        {
            this.___OnPropertyChanged("TargetInvestigationDate");
        }
        
        partial void OnIncidentLocationChanged()
        {
            this.___OnPropertyChanged("IncidentLocation");
        }
        
        partial void OnDateReportedChanged()
        {
            this.___OnPropertyChanged("DateReported");
        }
        
        partial void OnAdditionalCommentsChanged()
        {
            this.___OnPropertyChanged("AdditionalComments");
        }
        
        partial void OnImmediateActionChanged()
        {
            this.___OnPropertyChanged("ImmediateAction");
        }
        
        partial void OnInvestigationStartChanged()
        {
            this.___OnPropertyChanged("InvestigationStart");
        }
        
        partial void OnRootCauseIdentifiedChanged()
        {
            this.___OnPropertyChanged("RootCauseIdentified");
        }
        
        partial void OnPreventativeActionChanged()
        {
            this.___OnPropertyChanged("PreventativeAction");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass.IImplementation.ReportedBy
        {
            get
            {
                return this.ReportedBy;
            }
            set
            {
                this.ReportedBy = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __ReportedBy
        {
            get
            {
                if (this.___ReportedBy == null)
                {
                    this.___ReportedBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "ReportedBy",
                        new string[] { "HealthAndSafetyIncident_Employee1" },
                        e => global::System.Object.Equals(e.Id, this.HealthAndSafetyIncident_Employee1),
                        () => this._ReportedBy,
                        e => this._ReportedBy = e);
                }
                return this.___ReportedBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___ReportedBy;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass.IImplementation.IncidentStatus
        {
            get
            {
                return this.IncidentStatus;
            }
            set
            {
                this.IncidentStatus = (global::LightSwitchApplication.Implementation.IncidentStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IncidentStatus> __IncidentStatus
        {
            get
            {
                if (this.___IncidentStatus == null)
                {
                    this.___IncidentStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IncidentStatus>(
                        this,
                        "IncidentStatus",
                        new string[] { "IncidentStatus_HealthAndSafetyIncident" },
                        e => global::System.Object.Equals(e.Id, this.IncidentStatus_HealthAndSafetyIncident),
                        () => this._IncidentStatus,
                        e => this._IncidentStatus = e);
                }
                return this.___IncidentStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IncidentStatus> ___IncidentStatus;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass.IImplementation.IncidentWitnesses
        {
            get
            {
                return this.IncidentWitnesses;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentWitness> __IncidentWitnesses
        {
            get
            {
                if (this.___IncidentWitnesses == null)
                {
                    this.___IncidentWitnesses = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentWitness>(
                        this,
                        "IncidentWitnesses",
                        () => this._IncidentWitnesses,
                        e => global::System.Object.Equals(e.IncidentWitness_HealthAndSafetyIncident, this.Id));
                }
                return this.___IncidentWitnesses;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentWitness> ___IncidentWitnesses;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass.IImplementation.ReportedTo
        {
            get
            {
                return this.ReportedTo;
            }
            set
            {
                this.ReportedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __ReportedTo
        {
            get
            {
                if (this.___ReportedTo == null)
                {
                    this.___ReportedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "ReportedTo",
                        new string[] { "HealthAndSafetyIncident_Employee" },
                        e => global::System.Object.Equals(e.Id, this.HealthAndSafetyIncident_Employee),
                        () => this._ReportedTo,
                        e => this._ReportedTo = e);
                }
                return this.___ReportedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___ReportedTo;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass.IImplementation.IncidentPersons
        {
            get
            {
                return this.IncidentPersons;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> __IncidentPersons
        {
            get
            {
                if (this.___IncidentPersons == null)
                {
                    this.___IncidentPersons = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson>(
                        this,
                        "IncidentPersons",
                        () => this._IncidentPersons,
                        e => global::System.Object.Equals(e.IncidentPerson_HealthAndSafetyIncident, this.Id));
                }
                return this.___IncidentPersons;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> ___IncidentPersons;
        
    }
    #endregion
    
    #region IncidentOutcome
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IncidentOutcome :
        global::LightSwitchApplication.IncidentOutcome.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnOutcomeChanged()
        {
            this.___OnPropertyChanged("Outcome");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.IncidentOutcome.DetailsClass.IImplementation.IncidentPerson
        {
            get
            {
                return this.IncidentPerson;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> __IncidentPerson
        {
            get
            {
                if (this.___IncidentPerson == null)
                {
                    this.___IncidentPerson = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson>(
                        this,
                        "IncidentPerson",
                        () => this._IncidentPerson,
                        e => global::System.Object.Equals(e.IncidentOutcome_IncidentPerson, this.Id));
                }
                return this.___IncidentPerson;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> ___IncidentPerson;
        
    }
    #endregion
    
    #region IncidentPerson
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IncidentPerson :
        global::LightSwitchApplication.IncidentPerson.DetailsClass.IImplementation
    {
        partial void OnIncidentPerson_PersonTypeChanged()
        {
            this.___OnPropertyChanged("IncidentPerson_PersonType");
            this.___OnPropertyChanged("PersonType");
        }
        
        partial void OnInjuryType_IncidentPersonChanged()
        {
            this.___OnPropertyChanged("InjuryType_IncidentPerson");
            this.___OnPropertyChanged("InjuryType");
        }
        
        partial void OnIncidentOutcome_IncidentPersonChanged()
        {
            this.___OnPropertyChanged("IncidentOutcome_IncidentPerson");
            this.___OnPropertyChanged("IncidentOutcomes");
        }
        
        partial void OnIncidentPerson_HealthAndSafetyIncidentChanged()
        {
            this.___OnPropertyChanged("IncidentPerson_HealthAndSafetyIncident");
            this.___OnPropertyChanged("HealthAndSafetyIncident");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnIncidentPersonSurnameChanged()
        {
            this.___OnPropertyChanged("IncidentPersonSurname");
        }
        
        partial void OnIncidentPersonForenameChanged()
        {
            this.___OnPropertyChanged("IncidentPersonForename");
        }
        
        partial void OnOccupationChanged()
        {
            this.___OnPropertyChanged("Occupation");
        }
        
        partial void OnWorkDaysLostChanged()
        {
            this.___OnPropertyChanged("WorkDaysLost");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IncidentPerson.DetailsClass.IImplementation.PersonType
        {
            get
            {
                return this.PersonType;
            }
            set
            {
                this.PersonType = (global::LightSwitchApplication.Implementation.PersonType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PersonType> __PersonType
        {
            get
            {
                if (this.___PersonType == null)
                {
                    this.___PersonType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PersonType>(
                        this,
                        "PersonType",
                        new string[] { "IncidentPerson_PersonType" },
                        e => global::System.Object.Equals(e.Id, this.IncidentPerson_PersonType),
                        () => this._PersonType,
                        e => this._PersonType = e);
                }
                return this.___PersonType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PersonType> ___PersonType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IncidentPerson.DetailsClass.IImplementation.InjuryType
        {
            get
            {
                return this.InjuryType;
            }
            set
            {
                this.InjuryType = (global::LightSwitchApplication.Implementation.InjuryType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.InjuryType> __InjuryType
        {
            get
            {
                if (this.___InjuryType == null)
                {
                    this.___InjuryType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.InjuryType>(
                        this,
                        "InjuryType",
                        new string[] { "InjuryType_IncidentPerson" },
                        e => global::System.Object.Equals(e.Id, this.InjuryType_IncidentPerson),
                        () => this._InjuryType,
                        e => this._InjuryType = e);
                }
                return this.___InjuryType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.InjuryType> ___InjuryType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IncidentPerson.DetailsClass.IImplementation.IncidentOutcomes
        {
            get
            {
                return this.IncidentOutcomes;
            }
            set
            {
                this.IncidentOutcomes = (global::LightSwitchApplication.Implementation.IncidentOutcome)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IncidentOutcome> __IncidentOutcomes
        {
            get
            {
                if (this.___IncidentOutcomes == null)
                {
                    this.___IncidentOutcomes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IncidentOutcome>(
                        this,
                        "IncidentOutcomes",
                        new string[] { "IncidentOutcome_IncidentPerson" },
                        e => global::System.Object.Equals(e.Id, this.IncidentOutcome_IncidentPerson),
                        () => this._IncidentOutcomes,
                        e => this._IncidentOutcomes = e);
                }
                return this.___IncidentOutcomes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IncidentOutcome> ___IncidentOutcomes;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IncidentPerson.DetailsClass.IImplementation.HealthAndSafetyIncident
        {
            get
            {
                return this.HealthAndSafetyIncident;
            }
            set
            {
                this.HealthAndSafetyIncident = (global::LightSwitchApplication.Implementation.HealthAndSafetyIncident)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> __HealthAndSafetyIncident
        {
            get
            {
                if (this.___HealthAndSafetyIncident == null)
                {
                    this.___HealthAndSafetyIncident = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident>(
                        this,
                        "HealthAndSafetyIncident",
                        new string[] { "IncidentPerson_HealthAndSafetyIncident" },
                        e => global::System.Object.Equals(e.Id, this.IncidentPerson_HealthAndSafetyIncident),
                        () => this._HealthAndSafetyIncident,
                        e => this._HealthAndSafetyIncident = e);
                }
                return this.___HealthAndSafetyIncident;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> ___HealthAndSafetyIncident;
        
    }
    #endregion
    
    #region IncidentStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IncidentStatus :
        global::LightSwitchApplication.IncidentStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnStatusTypeChanged()
        {
            this.___OnPropertyChanged("StatusType");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.IncidentStatus.DetailsClass.IImplementation.HealthAndSafetyIncident
        {
            get
            {
                return this.HealthAndSafetyIncident;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> __HealthAndSafetyIncident
        {
            get
            {
                if (this.___HealthAndSafetyIncident == null)
                {
                    this.___HealthAndSafetyIncident = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident>(
                        this,
                        "HealthAndSafetyIncident",
                        () => this._HealthAndSafetyIncident,
                        e => global::System.Object.Equals(e.IncidentStatus_HealthAndSafetyIncident, this.Id));
                }
                return this.___HealthAndSafetyIncident;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> ___HealthAndSafetyIncident;
        
    }
    #endregion
    
    #region IncidentWitness
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IncidentWitness :
        global::LightSwitchApplication.IncidentWitness.DetailsClass.IImplementation
    {
        partial void OnIncidentWitness_PersonTypeChanged()
        {
            this.___OnPropertyChanged("IncidentWitness_PersonType");
            this.___OnPropertyChanged("PersonType");
        }
        
        partial void OnIncidentWitness_HealthAndSafetyIncidentChanged()
        {
            this.___OnPropertyChanged("IncidentWitness_HealthAndSafetyIncident");
            this.___OnPropertyChanged("HealthAndSafetyIncident");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnSurnameChanged()
        {
            this.___OnPropertyChanged("Surname");
        }
        
        partial void OnForenameChanged()
        {
            this.___OnPropertyChanged("Forename");
        }
        
        partial void OnPhoneChanged()
        {
            this.___OnPropertyChanged("Phone");
        }
        
        partial void OnEMailChanged()
        {
            this.___OnPropertyChanged("EMail");
        }
        
        partial void OnStatementChanged()
        {
            this.___OnPropertyChanged("Statement");
        }
        
        partial void OnStatementDateChanged()
        {
            this.___OnPropertyChanged("StatementDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IncidentWitness.DetailsClass.IImplementation.PersonType
        {
            get
            {
                return this.PersonType;
            }
            set
            {
                this.PersonType = (global::LightSwitchApplication.Implementation.PersonType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PersonType> __PersonType
        {
            get
            {
                if (this.___PersonType == null)
                {
                    this.___PersonType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PersonType>(
                        this,
                        "PersonType",
                        new string[] { "IncidentWitness_PersonType" },
                        e => global::System.Object.Equals(e.Id, this.IncidentWitness_PersonType),
                        () => this._PersonType,
                        e => this._PersonType = e);
                }
                return this.___PersonType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PersonType> ___PersonType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IncidentWitness.DetailsClass.IImplementation.HealthAndSafetyIncident
        {
            get
            {
                return this.HealthAndSafetyIncident;
            }
            set
            {
                this.HealthAndSafetyIncident = (global::LightSwitchApplication.Implementation.HealthAndSafetyIncident)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> __HealthAndSafetyIncident
        {
            get
            {
                if (this.___HealthAndSafetyIncident == null)
                {
                    this.___HealthAndSafetyIncident = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident>(
                        this,
                        "HealthAndSafetyIncident",
                        new string[] { "IncidentWitness_HealthAndSafetyIncident" },
                        e => global::System.Object.Equals(e.Id, this.IncidentWitness_HealthAndSafetyIncident),
                        () => this._HealthAndSafetyIncident,
                        e => this._HealthAndSafetyIncident = e);
                }
                return this.___HealthAndSafetyIncident;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HealthAndSafetyIncident> ___HealthAndSafetyIncident;
        
    }
    #endregion
    
    #region InjuryType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class InjuryType :
        global::LightSwitchApplication.InjuryType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnInjuryChanged()
        {
            this.___OnPropertyChanged("Injury");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.InjuryType.DetailsClass.IImplementation.IncidentPersons
        {
            get
            {
                return this.IncidentPersons;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> __IncidentPersons
        {
            get
            {
                if (this.___IncidentPersons == null)
                {
                    this.___IncidentPersons = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson>(
                        this,
                        "IncidentPersons",
                        () => this._IncidentPersons,
                        e => global::System.Object.Equals(e.InjuryType_IncidentPerson, this.Id));
                }
                return this.___IncidentPersons;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> ___IncidentPersons;
        
    }
    #endregion
    
    #region PersonType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PersonType :
        global::LightSwitchApplication.PersonType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnTypeOfPersonChanged()
        {
            this.___OnPropertyChanged("TypeOfPerson");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.PersonType.DetailsClass.IImplementation.IncidentPersons
        {
            get
            {
                return this.IncidentPersons;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> __IncidentPersons
        {
            get
            {
                if (this.___IncidentPersons == null)
                {
                    this.___IncidentPersons = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson>(
                        this,
                        "IncidentPersons",
                        () => this._IncidentPersons,
                        e => global::System.Object.Equals(e.IncidentPerson_PersonType, this.Id));
                }
                return this.___IncidentPersons;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentPerson> ___IncidentPersons;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.PersonType.DetailsClass.IImplementation.IncidentWitnesses
        {
            get
            {
                return this.IncidentWitnesses;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentWitness> __IncidentWitnesses
        {
            get
            {
                if (this.___IncidentWitnesses == null)
                {
                    this.___IncidentWitnesses = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentWitness>(
                        this,
                        "IncidentWitnesses",
                        () => this._IncidentWitnesses,
                        e => global::System.Object.Equals(e.IncidentWitness_PersonType, this.Id));
                }
                return this.___IncidentWitnesses;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IncidentWitness> ___IncidentWitnesses;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.HealthAndSafetyIncident))
            {
                return new global::LightSwitchApplication.Implementation.HealthAndSafetyIncident();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IncidentOutcome))
            {
                return new global::LightSwitchApplication.Implementation.IncidentOutcome();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IncidentPerson))
            {
                return new global::LightSwitchApplication.Implementation.IncidentPerson();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IncidentStatus))
            {
                return new global::LightSwitchApplication.Implementation.IncidentStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IncidentWitness))
            {
                return new global::LightSwitchApplication.Implementation.IncidentWitness();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.InjuryType))
            {
                return new global::LightSwitchApplication.Implementation.InjuryType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PersonType))
            {
                return new global::LightSwitchApplication.Implementation.PersonType();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.HealthAndSafetyIncident) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.HealthAndSafetyIncident);
            }
            if (typeof(global::LightSwitchApplication.IncidentOutcome) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IncidentOutcome);
            }
            if (typeof(global::LightSwitchApplication.IncidentPerson) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IncidentPerson);
            }
            if (typeof(global::LightSwitchApplication.IncidentStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IncidentStatus);
            }
            if (typeof(global::LightSwitchApplication.IncidentWitness) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IncidentWitness);
            }
            if (typeof(global::LightSwitchApplication.InjuryType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.InjuryType);
            }
            if (typeof(global::LightSwitchApplication.PersonType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PersonType);
            }
            return null;
        }
    }
}
