

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class IncidentPerson : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the IncidentPerson entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IncidentPerson()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IncidentPerson(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IncidentPerson> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.IncidentPerson.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPerson_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPerson_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string IncidentPersonSurname
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentPersonSurname);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentPersonSurname, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPersonSurname_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPersonSurname_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPersonSurname_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string IncidentPersonForename
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentPersonForename);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentPersonForename, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPersonForename_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPersonForename_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentPersonForename_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Occupation
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Occupation);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Occupation, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Occupation_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Occupation_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Occupation_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int WorkDaysLost
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.WorkDaysLost);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.WorkDaysLost, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkDaysLost_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkDaysLost_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkDaysLost_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.PersonType PersonType
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.PersonType);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.PersonType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.InjuryType InjuryType
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.InjuryType);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.InjuryType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InjuryType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InjuryType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InjuryType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.IncidentOutcome IncidentOutcomes
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentOutcomes);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentOutcomes, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentOutcomes_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentOutcomes_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentOutcomes_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.HealthAndSafetyIncident HealthAndSafetyIncident
        {
            get
            {
                return global::LightSwitchApplication.IncidentPerson.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.HealthAndSafetyIncident);
            }
            set
            {
                global::LightSwitchApplication.IncidentPerson.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HealthAndSafetyIncident_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HealthAndSafetyIncident_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HealthAndSafetyIncident_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.IncidentPerson,
                global::LightSwitchApplication.IncidentPerson.DetailsClass,
                global::LightSwitchApplication.IncidentPerson.DetailsClass.IImplementation,
                global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>.Entry
                __IncidentPersonEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>.Entry(
                    global::LightSwitchApplication.IncidentPerson.DetailsClass.__IncidentPerson_CreateNew,
                    global::LightSwitchApplication.IncidentPerson.DetailsClass.__IncidentPerson_Created,
                    global::LightSwitchApplication.IncidentPerson.DetailsClass.__IncidentPerson_AllowSaveWithErrors);
            private static global::LightSwitchApplication.IncidentPerson __IncidentPerson_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IncidentPerson> es)
            {
                return new global::LightSwitchApplication.IncidentPerson(es);
            }
            private static void __IncidentPerson_Created(global::LightSwitchApplication.IncidentPerson e)
            {
                e.IncidentPerson_Created();
            }
            private static bool __IncidentPerson_AllowSaveWithErrors(global::LightSwitchApplication.IncidentPerson e)
            {
                bool result = false;
                e.IncidentPerson_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string> IncidentPersonSurname
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentPersonSurname) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string> IncidentPersonForename
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentPersonForename) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string> Occupation
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Occupation) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int> WorkDaysLost
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.WorkDaysLost) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.PersonType> PersonType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.PersonType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.PersonType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.InjuryType> InjuryType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.InjuryType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.InjuryType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.IncidentOutcome> IncidentOutcomes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentOutcomes) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.IncidentOutcome>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident> HealthAndSafetyIncident
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.HealthAndSafetyIncident) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string IncidentPersonSurname { get; set; }
                new string IncidentPersonForename { get; set; }
                new string Occupation { get; set; }
                new int WorkDaysLost { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation PersonType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation InjuryType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation IncidentOutcomes { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation HealthAndSafetyIncident { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry
                    IncidentPersonSurname = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry(
                        "IncidentPersonSurname",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonSurname_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonSurname_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonSurname_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonSurname_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonSurname_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonSurname_OnValueChanged);
                private static void _IncidentPersonSurname_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._IncidentPersonSurname, sf);
                }
                private static bool _IncidentPersonSurname_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.IncidentPersonSurname_IsReadOnly(ref result);
                    return result;
                }
                private static void _IncidentPersonSurname_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IncidentPersonSurname_Validate(r);
                }
                private static string _IncidentPersonSurname_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.IncidentPersonSurname;
                }
                private static void _IncidentPersonSurname_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, string v)
                {
                    d.ImplementationEntity.IncidentPersonSurname = v;
                }
                private static void _IncidentPersonSurname_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.IncidentPersonSurname_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry
                    IncidentPersonForename = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry(
                        "IncidentPersonForename",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonForename_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonForename_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonForename_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonForename_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonForename_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentPersonForename_OnValueChanged);
                private static void _IncidentPersonForename_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._IncidentPersonForename, sf);
                }
                private static bool _IncidentPersonForename_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.IncidentPersonForename_IsReadOnly(ref result);
                    return result;
                }
                private static void _IncidentPersonForename_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IncidentPersonForename_Validate(r);
                }
                private static string _IncidentPersonForename_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.IncidentPersonForename;
                }
                private static void _IncidentPersonForename_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, string v)
                {
                    d.ImplementationEntity.IncidentPersonForename = v;
                }
                private static void _IncidentPersonForename_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.IncidentPersonForename_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry
                    Occupation = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry(
                        "Occupation",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Occupation_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Occupation_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Occupation_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Occupation_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Occupation_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Occupation_OnValueChanged);
                private static void _Occupation_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._Occupation, sf);
                }
                private static bool _Occupation_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.Occupation_IsReadOnly(ref result);
                    return result;
                }
                private static void _Occupation_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Occupation_Validate(r);
                }
                private static string _Occupation_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.Occupation;
                }
                private static void _Occupation_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Occupation = v;
                }
                private static void _Occupation_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.Occupation_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Entry
                    WorkDaysLost = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Entry(
                        "WorkDaysLost",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._WorkDaysLost_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._WorkDaysLost_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._WorkDaysLost_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._WorkDaysLost_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._WorkDaysLost_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._WorkDaysLost_OnValueChanged);
                private static void _WorkDaysLost_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._WorkDaysLost, sf);
                }
                private static bool _WorkDaysLost_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.WorkDaysLost_IsReadOnly(ref result);
                    return result;
                }
                private static void _WorkDaysLost_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.WorkDaysLost_Validate(r);
                }
                private static int _WorkDaysLost_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.WorkDaysLost;
                }
                private static void _WorkDaysLost_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, int v)
                {
                    d.ImplementationEntity.WorkDaysLost = v;
                }
                private static void _WorkDaysLost_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.WorkDaysLost_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.PersonType>.Entry
                    PersonType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.PersonType>.Entry(
                        "PersonType",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_GetCoreImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_Refresh,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._PersonType_OnValueChanged);
                private static void _PersonType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.PersonType>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._PersonType, sf);
                }
                private static bool _PersonType_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.PersonType_IsReadOnly(ref result);
                    return result;
                }
                private static void _PersonType_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PersonType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _PersonType_GetCoreImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.PersonType;
                }
                private static global::LightSwitchApplication.PersonType _PersonType_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.PersonType, global::LightSwitchApplication.PersonType.DetailsClass>(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType);
                }
                private static void _PersonType_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, global::LightSwitchApplication.PersonType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType, (i, ev) => i.PersonType = ev, v);
                }
                private static void _PersonType_Refresh(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType);
                }
                private static void _PersonType_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.PersonType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.InjuryType>.Entry
                    InjuryType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.InjuryType>.Entry(
                        "InjuryType",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_GetCoreImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_Refresh,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._InjuryType_OnValueChanged);
                private static void _InjuryType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.InjuryType>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._InjuryType, sf);
                }
                private static bool _InjuryType_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.InjuryType_IsReadOnly(ref result);
                    return result;
                }
                private static void _InjuryType_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.InjuryType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _InjuryType_GetCoreImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.InjuryType;
                }
                private static global::LightSwitchApplication.InjuryType _InjuryType_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.InjuryType, global::LightSwitchApplication.InjuryType.DetailsClass>(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.InjuryType, ref d._InjuryType);
                }
                private static void _InjuryType_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, global::LightSwitchApplication.InjuryType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.InjuryType, ref d._InjuryType, (i, ev) => i.InjuryType = ev, v);
                }
                private static void _InjuryType_Refresh(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.InjuryType, ref d._InjuryType);
                }
                private static void _InjuryType_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.InjuryType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.IncidentOutcome>.Entry
                    IncidentOutcomes = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.IncidentOutcome>.Entry(
                        "IncidentOutcomes",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_GetCoreImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_Refresh,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._IncidentOutcomes_OnValueChanged);
                private static void _IncidentOutcomes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.IncidentOutcome>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._IncidentOutcomes, sf);
                }
                private static bool _IncidentOutcomes_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.IncidentOutcomes_IsReadOnly(ref result);
                    return result;
                }
                private static void _IncidentOutcomes_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IncidentOutcomes_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _IncidentOutcomes_GetCoreImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.IncidentOutcomes;
                }
                private static global::LightSwitchApplication.IncidentOutcome _IncidentOutcomes_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentOutcomes, ref d._IncidentOutcomes);
                }
                private static void _IncidentOutcomes_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, global::LightSwitchApplication.IncidentOutcome v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentOutcomes, ref d._IncidentOutcomes, (i, ev) => i.IncidentOutcomes = ev, v);
                }
                private static void _IncidentOutcomes_Refresh(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.IncidentOutcomes, ref d._IncidentOutcomes);
                }
                private static void _IncidentOutcomes_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.IncidentOutcomes_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Entry
                    HealthAndSafetyIncident = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Entry(
                        "HealthAndSafetyIncident",
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_Stub,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_Validate,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_GetCoreImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_GetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_SetImplementationValue,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_Refresh,
                        global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_OnValueChanged);
                private static void _HealthAndSafetyIncident_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentPerson.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Data> c, global::LightSwitchApplication.IncidentPerson.DetailsClass d, object sf)
                {
                    c(d, ref d._HealthAndSafetyIncident, sf);
                }
                private static bool _HealthAndSafetyIncident_ComputeIsReadOnly(global::LightSwitchApplication.IncidentPerson e)
                {
                    bool result = false;
                    e.HealthAndSafetyIncident_IsReadOnly(ref result);
                    return result;
                }
                private static void _HealthAndSafetyIncident_Validate(global::LightSwitchApplication.IncidentPerson e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HealthAndSafetyIncident_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _HealthAndSafetyIncident_GetCoreImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.ImplementationEntity.HealthAndSafetyIncident;
                }
                private static global::LightSwitchApplication.HealthAndSafetyIncident _HealthAndSafetyIncident_GetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.HealthAndSafetyIncident, global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass>(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, ref d._HealthAndSafetyIncident);
                }
                private static void _HealthAndSafetyIncident_SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass d, global::LightSwitchApplication.HealthAndSafetyIncident v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, ref d._HealthAndSafetyIncident, (i, ev) => i.HealthAndSafetyIncident = ev, v);
                }
                private static void _HealthAndSafetyIncident_Refresh(global::LightSwitchApplication.IncidentPerson.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.IncidentPerson.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, ref d._HealthAndSafetyIncident);
                }
                private static void _HealthAndSafetyIncident_OnValueChanged(global::LightSwitchApplication.IncidentPerson e)
                {
                    e.HealthAndSafetyIncident_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data _IncidentPersonSurname;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data _IncidentPersonForename;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data _Occupation;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, int>.Data _WorkDaysLost;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.PersonType>.Data _PersonType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.InjuryType>.Data _InjuryType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.IncidentOutcome>.Data _IncidentOutcomes;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Data _HealthAndSafetyIncident;
            
        }
    
        #endregion
    }
    
    #endregion
}
