

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class IncidentWitness : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the IncidentWitness entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IncidentWitness()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IncidentWitness(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IncidentWitness> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.IncidentWitness.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentWitness_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentWitness_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Surname
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Surname);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Surname, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Surname_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Surname_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Surname_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Forename
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Forename);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Forename, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Forename_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Forename_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Forename_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Phone
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Phone);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Phone, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EMail
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.EMail);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.EMail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EMail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EMail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EMail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Statement
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Statement);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Statement, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Statement_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Statement_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Statement_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> StatementDate
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.StatementDate);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.StatementDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StatementDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StatementDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StatementDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.PersonType PersonType
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.PersonType);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.PersonType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PersonType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.HealthAndSafetyIncident HealthAndSafetyIncident
        {
            get
            {
                return global::LightSwitchApplication.IncidentWitness.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.HealthAndSafetyIncident);
            }
            set
            {
                global::LightSwitchApplication.IncidentWitness.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HealthAndSafetyIncident_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HealthAndSafetyIncident_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HealthAndSafetyIncident_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.IncidentWitness,
                global::LightSwitchApplication.IncidentWitness.DetailsClass,
                global::LightSwitchApplication.IncidentWitness.DetailsClass.IImplementation,
                global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass>.Entry
                __IncidentWitnessEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass>.Entry(
                    global::LightSwitchApplication.IncidentWitness.DetailsClass.__IncidentWitness_CreateNew,
                    global::LightSwitchApplication.IncidentWitness.DetailsClass.__IncidentWitness_Created,
                    global::LightSwitchApplication.IncidentWitness.DetailsClass.__IncidentWitness_AllowSaveWithErrors);
            private static global::LightSwitchApplication.IncidentWitness __IncidentWitness_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IncidentWitness> es)
            {
                return new global::LightSwitchApplication.IncidentWitness(es);
            }
            private static void __IncidentWitness_Created(global::LightSwitchApplication.IncidentWitness e)
            {
                e.IncidentWitness_Created();
            }
            private static bool __IncidentWitness_AllowSaveWithErrors(global::LightSwitchApplication.IncidentWitness e)
            {
                bool result = false;
                e.IncidentWitness_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> Surname
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Surname) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> Forename
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Forename) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> Phone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Phone) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> EMail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.EMail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> Statement
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Statement) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTime>> StatementDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.StatementDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.PersonType> PersonType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.PersonType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.PersonType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident> HealthAndSafetyIncident
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.HealthAndSafetyIncident) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Surname { get; set; }
                new string Forename { get; set; }
                new string Phone { get; set; }
                new string EMail { get; set; }
                new string Statement { get; set; }
                new global::System.Nullable<global::System.DateTime> StatementDate { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation PersonType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation HealthAndSafetyIncident { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, int>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    Surname = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "Surname",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Surname_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Surname_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Surname_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Surname_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Surname_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Surname_OnValueChanged);
                private static void _Surname_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Surname, sf);
                }
                private static bool _Surname_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Surname_IsReadOnly(ref result);
                    return result;
                }
                private static void _Surname_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Surname_Validate(r);
                }
                private static string _Surname_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Surname;
                }
                private static void _Surname_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Surname = v;
                }
                private static void _Surname_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Surname_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    Forename = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "Forename",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Forename_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Forename_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Forename_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Forename_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Forename_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Forename_OnValueChanged);
                private static void _Forename_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Forename, sf);
                }
                private static bool _Forename_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Forename_IsReadOnly(ref result);
                    return result;
                }
                private static void _Forename_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Forename_Validate(r);
                }
                private static string _Forename_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Forename;
                }
                private static void _Forename_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Forename = v;
                }
                private static void _Forename_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Forename_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    Phone = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "Phone",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Phone_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Phone_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Phone_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Phone_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Phone_OnValueChanged);
                private static void _Phone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Phone, sf);
                }
                private static bool _Phone_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Phone_IsReadOnly(ref result);
                    return result;
                }
                private static void _Phone_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Phone_Validate(r);
                }
                private static string _Phone_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Phone;
                }
                private static void _Phone_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Phone = v;
                }
                private static void _Phone_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Phone_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    EMail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "EMail",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._EMail_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._EMail_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._EMail_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._EMail_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._EMail_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._EMail_OnValueChanged);
                private static void _EMail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._EMail, sf);
                }
                private static bool _EMail_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.EMail_IsReadOnly(ref result);
                    return result;
                }
                private static void _EMail_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EMail_Validate(r);
                }
                private static string _EMail_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.EMail;
                }
                private static void _EMail_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EMail = v;
                }
                private static void _EMail_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.EMail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    Statement = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "Statement",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Statement_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Statement_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Statement_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Statement_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Statement_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Statement_OnValueChanged);
                private static void _Statement_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Statement, sf);
                }
                private static bool _Statement_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Statement_IsReadOnly(ref result);
                    return result;
                }
                private static void _Statement_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Statement_Validate(r);
                }
                private static string _Statement_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Statement;
                }
                private static void _Statement_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Statement = v;
                }
                private static void _Statement_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Statement_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    StatementDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "StatementDate",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._StatementDate_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._StatementDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._StatementDate_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._StatementDate_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._StatementDate_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._StatementDate_OnValueChanged);
                private static void _StatementDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._StatementDate, sf);
                }
                private static bool _StatementDate_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.StatementDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _StatementDate_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StatementDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _StatementDate_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.StatementDate;
                }
                private static void _StatementDate_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.StatementDate = global::LightSwitchApplication.IncidentWitness.DetailsClass.TruncateDate(v);
                }
                private static void _StatementDate_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.StatementDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.PersonType>.Entry
                    PersonType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.PersonType>.Entry(
                        "PersonType",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_GetCoreImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_Refresh,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._PersonType_OnValueChanged);
                private static void _PersonType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.PersonType>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._PersonType, sf);
                }
                private static bool _PersonType_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.PersonType_IsReadOnly(ref result);
                    return result;
                }
                private static void _PersonType_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PersonType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _PersonType_GetCoreImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.PersonType;
                }
                private static global::LightSwitchApplication.PersonType _PersonType_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.PersonType, global::LightSwitchApplication.PersonType.DetailsClass>(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType);
                }
                private static void _PersonType_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, global::LightSwitchApplication.PersonType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType, (i, ev) => i.PersonType = ev, v);
                }
                private static void _PersonType_Refresh(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.PersonType, ref d._PersonType);
                }
                private static void _PersonType_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.PersonType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Entry
                    HealthAndSafetyIncident = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Entry(
                        "HealthAndSafetyIncident",
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_Stub,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_Validate,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_GetCoreImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_GetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_SetImplementationValue,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_Refresh,
                        global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties._HealthAndSafetyIncident_OnValueChanged);
                private static void _HealthAndSafetyIncident_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentWitness.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Data> c, global::LightSwitchApplication.IncidentWitness.DetailsClass d, object sf)
                {
                    c(d, ref d._HealthAndSafetyIncident, sf);
                }
                private static bool _HealthAndSafetyIncident_ComputeIsReadOnly(global::LightSwitchApplication.IncidentWitness e)
                {
                    bool result = false;
                    e.HealthAndSafetyIncident_IsReadOnly(ref result);
                    return result;
                }
                private static void _HealthAndSafetyIncident_Validate(global::LightSwitchApplication.IncidentWitness e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HealthAndSafetyIncident_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _HealthAndSafetyIncident_GetCoreImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.ImplementationEntity.HealthAndSafetyIncident;
                }
                private static global::LightSwitchApplication.HealthAndSafetyIncident _HealthAndSafetyIncident_GetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.HealthAndSafetyIncident, global::LightSwitchApplication.HealthAndSafetyIncident.DetailsClass>(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, ref d._HealthAndSafetyIncident);
                }
                private static void _HealthAndSafetyIncident_SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass d, global::LightSwitchApplication.HealthAndSafetyIncident v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, ref d._HealthAndSafetyIncident, (i, ev) => i.HealthAndSafetyIncident = ev, v);
                }
                private static void _HealthAndSafetyIncident_Refresh(global::LightSwitchApplication.IncidentWitness.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.IncidentWitness.DetailsClass.PropertySetProperties.HealthAndSafetyIncident, ref d._HealthAndSafetyIncident);
                }
                private static void _HealthAndSafetyIncident_OnValueChanged(global::LightSwitchApplication.IncidentWitness e)
                {
                    e.HealthAndSafetyIncident_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _Surname;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _Forename;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _Phone;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _EMail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _Statement;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _StatementDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.PersonType>.Data _PersonType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.IncidentWitness, global::LightSwitchApplication.IncidentWitness.DetailsClass, global::LightSwitchApplication.HealthAndSafetyIncident>.Data _HealthAndSafetyIncident;
            
        }
    
        #endregion
    }
    
    #endregion
}
