

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class IncidentOutcome : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the IncidentOutcome entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IncidentOutcome()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IncidentOutcome(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IncidentOutcome> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.IncidentOutcome.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentOutcome_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IncidentOutcome_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.IncidentOutcome.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Outcome
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Outcome);
            }
            set
            {
                global::LightSwitchApplication.IncidentOutcome.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Outcome, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Outcome_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Outcome_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Outcome_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.IncidentOutcome.DetailsClass.SetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.IncidentPerson> IncidentPerson
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetValue(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.IncidentPerson);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.IncidentPerson> IncidentPersonQuery
        {
            get
            {
                return global::LightSwitchApplication.IncidentOutcome.DetailsClass.GetQuery(this, global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.IncidentPerson);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.IncidentOutcome,
                global::LightSwitchApplication.IncidentOutcome.DetailsClass,
                global::LightSwitchApplication.IncidentOutcome.DetailsClass.IImplementation,
                global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>.Entry
                __IncidentOutcomeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>.Entry(
                    global::LightSwitchApplication.IncidentOutcome.DetailsClass.__IncidentOutcome_CreateNew,
                    global::LightSwitchApplication.IncidentOutcome.DetailsClass.__IncidentOutcome_Created,
                    global::LightSwitchApplication.IncidentOutcome.DetailsClass.__IncidentOutcome_AllowSaveWithErrors);
            private static global::LightSwitchApplication.IncidentOutcome __IncidentOutcome_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IncidentOutcome> es)
            {
                return new global::LightSwitchApplication.IncidentOutcome(es);
            }
            private static void __IncidentOutcome_Created(global::LightSwitchApplication.IncidentOutcome e)
            {
                e.IncidentOutcome_Created();
            }
            private static bool __IncidentOutcome_AllowSaveWithErrors(global::LightSwitchApplication.IncidentOutcome e)
            {
                bool result = false;
                e.IncidentOutcome_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string> Outcome
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Outcome) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::LightSwitchApplication.IncidentPerson> IncidentPerson
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.IncidentPerson) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::LightSwitchApplication.IncidentPerson>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Outcome { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable IncidentPerson { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, int>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Entry
                    Outcome = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Entry(
                        "Outcome",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Outcome_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Outcome_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Outcome_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Outcome_GetImplementationValue,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Outcome_SetImplementationValue,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Outcome_OnValueChanged);
                private static void _Outcome_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._Outcome, sf);
                }
                private static bool _Outcome_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.Outcome_IsReadOnly(ref result);
                    return result;
                }
                private static void _Outcome_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Outcome_Validate(r);
                }
                private static string _Outcome_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.Outcome;
                }
                private static void _Outcome_SetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Outcome = v;
                }
                private static void _Outcome_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.Outcome_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.IncidentOutcome e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.IncidentOutcome e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.IncidentOutcome.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.IncidentOutcome e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::LightSwitchApplication.IncidentPerson>.Entry
                    IncidentPerson = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::LightSwitchApplication.IncidentPerson>.Entry(
                        "IncidentPerson",
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._IncidentPerson_Stub,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._IncidentPerson_GetReferencedEntities,
                        global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties._IncidentPerson_GetEntityCollection);
                private static void _IncidentPerson_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::LightSwitchApplication.IncidentPerson>.Data> c, global::LightSwitchApplication.IncidentOutcome.DetailsClass d, object sf)
                {
                    c(d, ref d._IncidentPerson, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.IncidentPerson> _IncidentPerson_GetReferencedEntities(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.IncidentPerson, global::LightSwitchApplication.IncidentPerson.DetailsClass>(global::LightSwitchApplication.IncidentOutcome.DetailsClass.PropertySetProperties.IncidentPerson, ref d._IncidentPerson);
                }
                private static global::System.Collections.IEnumerable _IncidentPerson_GetEntityCollection(global::LightSwitchApplication.IncidentOutcome.DetailsClass d)
                {
                    return d.ImplementationEntity.IncidentPerson;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Data _Outcome;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.IncidentOutcome, global::LightSwitchApplication.IncidentOutcome.DetailsClass, global::LightSwitchApplication.IncidentPerson>.Data _IncidentPerson;
            
        }
    
        #endregion
    }
    
    #endregion
}
